CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"

DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_VIDEO_PATCH_TOKEN = "<vid_patch>"
# DEFAULT_SLOW_VIDEO_PATCH_TOKEN = "<slow_vid_patch>"
DEFAULT_VID_START_TOKEN = "<vid_start>"
DEFAULT_VID_END_TOKEN = "<vid_end>"
DEFAULT_SLOW_VID_START_TOKEN = "<slow_vid_start>"
DEFAULT_SLOW_VID_END_TOKEN = "<slow_vid_end>"

TEMPORAL_INPUT_TOKEN = '<TEMP-INPUT>'
TEMPORAL_OUTPUT_TOKEN = '<TEMP-OUTPUT>'
TEMPORAL_TOKEN_FORMAT = '<TEMP-{:03d}>'

SPATIAL_HEIGHT_INPUT_TOKEN = '<HEIGHT-INPUT>'
SPATIAL_HEIGHT_OUTPUT_TOKEN = '<HEIGHT-OUTPUT>'
SPATIAL_HEIGHT_TOKEN_FORMAT = '<HEIGHT-{:03d}>'

SPATIAL_WIDTH_INPUT_TOKEN = '<WIDTH-INPUT>'
SPATIAL_WIDTH_OUTPUT_TOKEN = '<WIDTH-OUTPUT>'
SPATIAL_WIDTH_TOKEN_FORMAT = '<WIDTH-{:03d}>'